    struct RClass *raft_msg_class;

    raft_msg_class = mrb_define_class (mrb, "RaftMsg", mrb->object_class);
    MRB_SET_INSTANCE_TT(raft_msg_class, MRB_TT_DATA);
    int ai = mrb_gc_arena_save (mrb);
    mrb_define_const (mrb, raft_msg_class, "SIGNATURE", mrb_fixnum_value(6));
    mrb_gc_arena_restore (mrb, ai);
    mrb_define_const (mrb, raft_msg_class, "APPENDENTRY", mrb_fixnum_value (1));
    mrb_gc_arena_restore (mrb, ai);
    mrb_define_const (mrb, raft_msg_class, "APPENDENTRY_REPLY", mrb_fixnum_value (2));
    mrb_gc_arena_restore (mrb, ai);
    mrb_define_const (mrb, raft_msg_class, "REQUESTVOTE", mrb_fixnum_value (3));
    mrb_gc_arena_restore (mrb, ai);
    mrb_define_const (mrb, raft_msg_class, "REQUESTVOTE_REPLY", mrb_fixnum_value (4));
    mrb_gc_arena_restore (mrb, ai);
    mrb_define_method (mrb, raft_msg_class, "initialize", mrb_raft_msg_initialize, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "recv", mrb_raft_msg_recv, MRB_ARGS_REQ(1));
    mrb_define_method (mrb, raft_msg_class, "send", mrb_raft_msg_send, MRB_ARGS_REQ(1));
    mrb_define_method (mrb, raft_msg_class, "print", mrb_raft_msg_print, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "routing_id", mrb_raft_msg_routing_id, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "routing_id=", mrb_raft_msg_set_routing_id, MRB_ARGS_REQ(1));
    mrb_define_method (mrb, raft_msg_class, "id", mrb_raft_msg_id, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "id=", mrb_raft_msg_set_id, MRB_ARGS_REQ(1));
    mrb_define_method (mrb, raft_msg_class, "command", mrb_raft_msg_command, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "term", mrb_raft_msg_term, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "term=", mrb_raft_msg_set_term, MRB_ARGS_REQ(1));
    mrb_define_method (mrb, raft_msg_class, "prevlogindex", mrb_raft_msg_prevlogindex, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "prevlogindex=", mrb_raft_msg_set_prevlogindex, MRB_ARGS_REQ(1));
    mrb_define_method (mrb, raft_msg_class, "prevlogterm", mrb_raft_msg_prevlogterm, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "prevlogterm=", mrb_raft_msg_set_prevlogterm, MRB_ARGS_REQ(1));
    mrb_define_method (mrb, raft_msg_class, "entry", mrb_raft_msg_entry, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "entry=", mrb_raft_msg_set_entry, MRB_ARGS_REQ(1));
    mrb_define_method (mrb, raft_msg_class, "leadercommit", mrb_raft_msg_leadercommit, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "leadercommit=", mrb_raft_msg_set_leadercommit, MRB_ARGS_REQ(1));
    mrb_define_method (mrb, raft_msg_class, "success", mrb_raft_msg_success, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "success=", mrb_raft_msg_set_success, MRB_ARGS_REQ(1));
    mrb_define_method (mrb, raft_msg_class, "lastlogindex", mrb_raft_msg_lastlogindex, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "lastlogindex=", mrb_raft_msg_set_lastlogindex, MRB_ARGS_REQ(1));
    mrb_define_method (mrb, raft_msg_class, "lastlogterm", mrb_raft_msg_lastlogterm, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "lastlogterm=", mrb_raft_msg_set_lastlogterm, MRB_ARGS_REQ(1));
    mrb_define_method (mrb, raft_msg_class, "votegranted", mrb_raft_msg_votegranted, MRB_ARGS_NONE());
    mrb_define_method (mrb, raft_msg_class, "votegranted=", mrb_raft_msg_set_votegranted, MRB_ARGS_REQ(1));
