The following ABNF grammar defines the raft over zyre:

    raft_msg        = *( APPENDENTRY | APPENDENTRY-REPLY | REQUESTVOTE | REQUESTVOTE-REPLY )

    ;  Invoked by leader to replicate log entries (§5.3); also used as      
    ;  heartbeat (§5.2).                                                    

    APPENDENTRY     = signature %d1 term prevlogindex prevlogterm entry leadercommit
    signature       = %xAA %xA6             ; two octets
    term            = number-8              ; leader's term
    prevlogindex    = number-8              ; index of log entry immediately preceding new ones
    prevlogterm     = number-8              ; term of prevLogIndex entry
    entry           = chunk                 ; log entry to store
    leadercommit    = number-8              ; leader’s commitIndex

    ;  No description                                                        

    APPENDENTRY-REPLY = signature %d2 term success
    term            = number-8              ; currentTerm, for leader to update itself
    success         = number-1              ; 1 if follower contained entry matching prevLogIndex and prevLogTerm

    ;  Invoked by candidates to gather votes (§5.2).                        

    REQUESTVOTE     = signature %d3 term lastlogindex lastlogterm
    term            = number-8              ; candidate’s term
    lastlogindex    = number-8              ; index of candidate’s last log entry (§5.4)
    lastlogterm     = number-8              ; term of candidate’s last log entry (§5.4)

    ;  No description                                                        

    REQUESTVOTE-REPLY = signature %d4 term votegranted
    term            = number-8              ; currentTerm, for candidate to update itself
    votegranted     = number-1              ; 1 means candidate received vote

    ; A chunk has 4-octet length + binary contents
    chunk           = number-4 *OCTET

    ; Strings are always length + text contents

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-4        = 4OCTET
    number-8        = 8OCTET
